#Importing the numpy module

In [0]:
import numpy as np

##Creating a numpy array

In [0]:
a=np.array([1,2,3])
b=np.array([1,2,3,4.55,6], dtype = np.int32)
b1=np.array([1,2,3,4.55,6], dtype = float)
print(a)
print(b)
print(b1)

[1 2 3]
[1 2 3 4 6]
[1.   2.   3.   4.55 6.  ]


##creating a 2-D and a 3-D array

In [0]:
my_mat = [[1,2,3], [4,5,6],[7,8,9] ]
s=np.array(my_mat)
print(s)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


##Creating a vector of various types 

In [0]:
a=np.linspace(0,5,100)
print(a)

[0.         0.05050505 0.1010101  0.15151515 0.2020202  0.25252525
 0.3030303  0.35353535 0.4040404  0.45454545 0.50505051 0.55555556
 0.60606061 0.65656566 0.70707071 0.75757576 0.80808081 0.85858586
 0.90909091 0.95959596 1.01010101 1.06060606 1.11111111 1.16161616
 1.21212121 1.26262626 1.31313131 1.36363636 1.41414141 1.46464646
 1.51515152 1.56565657 1.61616162 1.66666667 1.71717172 1.76767677
 1.81818182 1.86868687 1.91919192 1.96969697 2.02020202 2.07070707
 2.12121212 2.17171717 2.22222222 2.27272727 2.32323232 2.37373737
 2.42424242 2.47474747 2.52525253 2.57575758 2.62626263 2.67676768
 2.72727273 2.77777778 2.82828283 2.87878788 2.92929293 2.97979798
 3.03030303 3.08080808 3.13131313 3.18181818 3.23232323 3.28282828
 3.33333333 3.38383838 3.43434343 3.48484848 3.53535354 3.58585859
 3.63636364 3.68686869 3.73737374 3.78787879 3.83838384 3.88888889
 3.93939394 3.98989899 4.04040404 4.09090909 4.14141414 4.19191919
 4.24242424 4.29292929 4.34343434 4.39393939 4.44444444 4.4949

###The syntax is  np.arange(start, (end+1) , step(if any) )

In [0]:
s1=np.arange(0,11,2)
print(s1)

[ 0  2  4  6  8 10]


### Create an identity matrix

In [0]:
s2= np.eye(4)
print(s2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


##It is improtant to pass a tuple for the creation of a zero array

In [0]:
s3=np.zeros((3,4))
print(s3)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [0]:
s4=np.ones((3,4),dtype = float)
s4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

To create an array of random numbers  we use np.random.rand(diamension)

In [0]:
#This doesn't requrie us to pass a tuple for the creation of a radom array
s4 = np.random.rand(3,4)
print(s4)

[[0.07257128 0.66999563 0.51038686 0.66236631]
 [0.1554635  0.85439514 0.77440361 0.57536514]
 [0.09421892 0.07279712 0.9345516  0.65407346]]


### if we into gaussian stuff we can use the argument np.random.randn(diamension)

In [0]:
s5 = np.random.randn(3,4)
print(s5)

[[ 0.26980866  0.82824417 -0.49462774 -0.37618661]
 [ 0.86876525  1.54250358  1.37608474 -0.08202692]
 [-0.15463814 -1.05156683 -1.43003223 -1.01883592]]


If we only need random integers we use the function np.random.randint(start,end,diamension)

In [0]:
s6=np.random.randint(1,20000)
s7 =np.random.randint(1,20000,12)
#In this we are required to pass a tuple for the diamension if they are 2-d or 3-d
s8 = np.random.randint(1,20000,(3,4))
print(s6)
print(s7)
print(s8)

7572
[16883  2799 12618 13470 17952  3156  9912  8267 12168  7615 10433 10579]
[[ 1915 16699  1473 17072]
 [19436  4974  5362  3621]
 [ 9400  2105 15361  4212]]


#An application of array using numpy

### If you want to reshape an array to a different diamension then we use the thing called reshape 

In [0]:
s1=np.arange(25)
print(s1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [0]:
s2=np.random.randint(0,50,10)
print(s2)

[44 41  2 44 18 29  6 26 42 40]


In [0]:
s1.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#Indexing and Selection

In [0]:
#create a sample array
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


###The indexing of the array is similar to python list

In [0]:
print(arr[8])
print(arr[1:4:])

8
[1 2 3]


In [0]:
#if we want to  change the value of some elements to a specific value
arr[:5:]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [0]:
arr=np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [0]:
arr= np.array([[5,10,15],[20,25,30],[35,40,45]])
arr

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

To index a 2d array we use two ways

In [0]:
print(arr[0])
print(arr[0][0])

[ 5 10 15]
5


Or you can use

In [0]:
print(arr[2,1])
print(arr[0,0])

40
5


In [0]:
print(arr[:2])
print(arr[:2,1:])

[[ 5 10 15]
 [20 25 30]]
[[10 15]
 [25 30]]


#If you want to do some conditional selection

In [0]:
arr=np.arange(0,11)

In [0]:
p=np.array([0,1,2,3,4,5,6,7,8,9,10])

In [0]:
s = p > 5 
s

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [0]:
p[s]

array([ 6,  7,  8,  9, 10])

In [0]:
array_2d = np.arange(50).reshape(5,10)
print(array_2d)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [0]:
array_2d[3:5,5:8]

array([[35, 36, 37],
       [45, 46, 47]])

#Array operations

In [0]:
a1 = np.arange(0,11)

In [0]:
print(a1+a1)
print(a1*2)
print(a1+100)
print(a1//2)

[ 0  2  4  6  8 10 12 14 16 18 20]
[ 0  2  4  6  8 10 12 14 16 18 20]
[100 101 102 103 104 105 106 107 108 109 110]
[0 0 1 1 2 2 3 3 4 4 5]


In [0]:
print(a1/a1)
print(1/a1)

[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111 0.1       ]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


In [0]:
print(np.sqrt(a1))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766]
